// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1YwMHlZkILEmeYwWWcHjUFsLqIB4vfQ0',
    appId: '1:165619535126:web:f3dbf94073f490b6ce9437',
    messagingSenderId: '165619535126',
    projectId: 'tracker-1d28c',
    authDomain: 'tracker-1d28c.firebaseapp.com',
    storageBucket: 'tracker-1d28c.appspot.com',
    measurementId: 'G-0468NWC9HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRW5MrTxYS8tyU8n10FCbvZfhJemslyuM',
    appId: '1:165619535126:android:e6da295bff36c357ce9437',
    messagingSenderId: '165619535126',
    projectId: 'tracker-1d28c',
    storageBucket: 'tracker-1d28c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwiAqRlkSmXAaaoJ8eP6X-gzppbTuohxo',
    appId: '1:165619535126:ios:963f105e2c0ef8f7ce9437',
    messagingSenderId: '165619535126',
    projectId: 'tracker-1d28c',
    storageBucket: 'tracker-1d28c.appspot.com',
    androidClientId:
        '165619535126-7mmjk6mhts6cpvhm6qnbdj9q503i7q1v.apps.googleusercontent.com',
    iosClientId:
        '165619535126-jagolbg46rjh32j9r979h9ndkrm3p1ah.apps.googleusercontent.com',
    iosBundleId: 'me.raph.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwiAqRlkSmXAaaoJ8eP6X-gzppbTuohxo',
    appId: '1:165619535126:ios:963f105e2c0ef8f7ce9437',
    messagingSenderId: '165619535126',
    projectId: 'tracker-1d28c',
    storageBucket: 'tracker-1d28c.appspot.com',
    androidClientId:
        '165619535126-7mmjk6mhts6cpvhm6qnbdj9q503i7q1v.apps.googleusercontent.com',
    iosClientId:
        '165619535126-jagolbg46rjh32j9r979h9ndkrm3p1ah.apps.googleusercontent.com',
    iosBundleId: 'me.raph.tracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1YwMHlZkILEmeYwWWcHjUFsLqIB4vfQ0',
    appId: '1:165619535126:web:4bd10dd005e13c79ce9437',
    messagingSenderId: '165619535126',
    projectId: 'tracker-1d28c',
    authDomain: 'tracker-1d28c.firebaseapp.com',
    storageBucket: 'tracker-1d28c.appspot.com',
    measurementId: 'G-3LJ3W2R474',
  );

}