name: tracker
description: "Cross-platform workout tracking app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: 3.47.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  path_provider: ^2.1.6
  quiver: ^3.2.2
  hydrated_bloc: ^11.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.2
  build_runner: any
  husky: ^0.1.7

flutter:
  uses-material-design: true
