name: Dart

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tracker/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'tracker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_DIR: 'tracker'

    defaults:
      run:
        working-directory: ${{ env.APP_DIR }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v6
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: tracker/pubspec.yaml
        architecture: X64
    - name: Install Dependencies
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    - name: Verify generated code
      run: dart run build_runner build --delete-conflicting-outputs
    - name: Ensure generated code is committed
      working-directory: .
      run: git diff --exit-code -- tracker/**/*.g.dart
    - name: Run Tests
      run: flutter test